### ISSUE TITLE
Add mochitest runner

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-reps#1]

**Comment by nchevobbe** [comment]
What would it take to have this ? 
Do we need a docker image that then run the mochitest, like I think you do in the debugger ?

I would like to have this as soon as possible, it would makes me more confident doing all the reps work here instead of in mc

**Comment by jasonLaster** [comment]
I can work on this later today. 

It should be relatively easy to first copy our debugger scripts over and then we can generalize in the toolbox

**Comment by nchevobbe** [comment]
I'll try to look at https://bugzilla.mozilla.org/show_bug.cgi?id=1325401 today or tomorrow so we can tackle this

**Comment by juliandescottes** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1325401 is more or less ready to land.

I'll give this one a shot.
