### ISSUE TITLE
MC console should use the bundle

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-reps#29]
This issue tracks that

https://bugzilla.mozilla.org/show_bug.cgi?id=1325401

**Comment by jasonLaster** [comment]
@nchevobbe, @tromey 

Here's an *almost* working patch of the reps bundle in M-C

https://gist.github.com/jasonLaster/1f9cba50891b8648a8b4410a942aa685

When it's working, I'll make a patch. I think it makes sense to add the bundle as is as it will give us an opportunity to try it in nightly and experiment with the setup.

**Comment by juliandescottes** [comment]
Done!
