### ISSUE TITLE
Fix test_reps_object.html

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-reps#51]
We had to skip these tests to land mochitests in CI...
https://github.com/devtools-html/devtools-reps/pull/49/files#diff-db0ef46f94069cfccd55ae4c59fff8e8R24

The test results were: 334 💚  1 🔴 

Lets fix this soon though

**Comment by juliandescottes** [comment]
Reenabled the test in #57 and it seems to work.
