### ISSUE TITLE
eslint inconsistency between devtools-reps and mc

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/devtools-reps#58]
In load-reps.js we can't have "use strict"; at the top of the file because: 

>  6:1       error      'use strict' is unnecessary inside of modules  

Eslint enforces this when 

```
"env": {
    "es6": true,
}
```

Which is the case for devtools-reps (https://github.com/devtools-html/devtools-reps/blob/master/.eslintrc.js#L12).

But this fails eslint validation in mozilla central. 

So we can ignore eslint in load-reps but that's a bit sad. Unfortunately eslint doesn't support disabling environments in single files (https://github.com/eslint/eslint/issues/2614).

NB: Ultimately load reps should be removed in favor of just requiring the bundle, but in the meantime we need a solution compatible with both validation environments.

**Comment by nchevobbe** [comment]
I guess we could add "use strict" at the top of the file when we copy the file to assets ? 
I'm not fluent in node but I think this is doable

> NB: Ultimately load reps should be removed in favor of just requiring the bundle, but in the meantime we need a solution compatible with both validation environments.

:+1:
