### ISSUE TITLE
TypeError: PropRep is not a function

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/devtools-reps#63]
STR:
1) Open/load Rep tester
2) Execute an expression e.g. `5+5`
3) Click on `Hide expression packet` button
4) The expanded body shows only `Object` and there is an exception logged in the Console panel -> BUG

Honza

---
       
TypeError: PropRep is not a function
Stack trace:
getProps@http://localhost:8000/assets/build/reps.js:52745:23
wrapMethod/<@http://localhost:8000/assets/build/reps.js:798:17
propIterator@http://localhost:8000/assets/build/reps.js:52691:18
wrapMethod/<@http://localhost:8000/assets/build/reps.js:798:17
safePropIterator@http://localhost:8000/assets/build/reps.js:52671:15
wrapMethod/<@http://localhost:8000/assets/build/reps.js:798:17
Obj<.render<@http://localhost:8000/assets/build/reps.js:52763:18
wrapRender/<@http://localhost:8000/assets/build/reps.js:52086:15
wrapMethod/<@http://localhost:8000/assets/build/reps.js:798:17
_renderValidatedComponentWithoutOwnerOrContext@http://localhost:8000/assets/build/reps.js:7027:30
_renderValidatedComponent@http://localhost:8000/assets/build/reps.js:7047:28
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:6660:26
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountChildren@http://localhost:8000/assets/build/reps.js:15052:29
_createContentMarkup@http://localhost:8000/assets/build/reps.js:12235:28
mountComponent@http://localhost:8000/assets/build/reps.js:12123:25
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
_mountChildByNameAtIndex@http://localhost:8000/assets/build/reps.js:15285:25
_updateChildren@http://localhost:8000/assets/build/reps.js:15189:12
updateChildren@http://localhost:8000/assets/build/reps.js:15137:10
_updateDOMChildren@http://localhost:8000/assets/build/reps.js:12515:8
updateComponent@http://localhost:8000/assets/build/reps.js:12344:6
receiveComponent@http://localhost:8000/assets/build/reps.js:12289:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
updateChildren@http://localhost:8000/assets/build/reps.js:15396:10
_reconcilerUpdateChildren@http://localhost:8000/assets/build/reps.js:15027:19
_updateChildren@http://localhost:8000/assets/build/reps.js:15162:27
updateChildren@http://localhost:8000/assets/build/reps.js:15137:10
_updateDOMChildren@http://localhost:8000/assets/build/reps.js:12515:8
updateComponent@http://localhost:8000/assets/build/reps.js:12344:6
receiveComponent@http://localhost:8000/assets/build/reps.js:12289:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
_updateRenderedComponent@http://localhost:8000/assets/build/reps.js:7002:8
_performComponentUpdate@http://localhost:8000/assets/build/reps.js:6984:6
updateComponent@http://localhost:8000/assets/build/reps.js:6913:8
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
receiveComponent@http://localhost:8000/assets/build/reps.js:6845:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
updateChildren@http://localhost:8000/assets/build/reps.js:15396:10
_reconcilerUpdateChildren@http://localhost:8000/assets/build/reps.js:15027:19
_updateChildren@http://localhost:8000/assets/build/reps.js:15162:27
updateChildren@http://localhost:8000/assets/build/reps.js:15137:10
_updateDOMChildren@http://localhost:8000/assets/build/reps.js:12515:8
updateComponent@http://localhost:8000/assets/build/reps.js:12344:6
receiveComponent@http://localhost:8000/assets/build/reps.js:12289:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
_updateRenderedComponent@http://localhost:8000/assets/build/reps.js:7002:8
_performComponentUpdate@http://localhost:8000/assets/build/reps.js:6984:6
updateComponent@http://localhost:8000/assets/build/reps.js:6913:8
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
receiveComponent@http://localhost:8000/assets/build/reps.js:6845:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
updateChildren@http://localhost:8000/assets/build/reps.js:15396:10
_reconcilerUpdateChildren@http://localhost:8000/assets/build/reps.js:15027:19
_updateChildren@http://localhost:8000/assets/build/reps.js:15162:27
updateChildren@http://localhost:8000/assets/build/reps.js:15137:10
_updateDOMChildren@http://localhost:8000/assets/build/reps.js:12515:8
updateComponent@http://localhost:8000/assets/build/reps.js:12344:6
receiveComponent@http://localhost:8000/assets/build/reps.js:12289:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
_updateRenderedComponent@http://localhost:8000/assets/build/reps.js:7002:8
_performComponentUpdate@http://localhost:8000/assets/build/reps.js:6984:6
updateComponent@http://localhost:8000/assets/build/reps.js:6913:8
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
receiveComponent@http://localhost:8000/assets/build/reps.js:6845:6
receiveComponent@http://localhost:8000/assets/build/reps.js:5028:6
_updateRenderedComponent@http://localhost:8000/assets/build/reps.js:7002:8
_performComponentUpdate@http://localhost:8000/assets/build/reps.js:6984:6
updateComponent@http://localhost:8000/assets/build/reps.js:6913:8
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
performUpdateIfNecessary@http://localhost:8000/assets/build/reps.js:6861:8
performUpdateIfNecessary@http://localhost:8000/assets/build/reps.js:5043:6
runBatchedUpdates@http://localhost:8000/assets/build/reps.js:5623:6
perform@http://localhost:8000/assets/build/reps.js:6080:14
perform@http://localhost:8000/assets/build/reps.js:6080:14
perform@http://localhost:8000/assets/build/reps.js:5580:13
flushBatchedUpdates@http://localhost:8000/assets/build/reps.js:5641:8
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
closeAll@http://localhost:8000/assets/build/reps.js:6146:12
perform@http://localhost:8000/assets/build/reps.js:6093:12
batchedUpdates@http://localhost:8000/assets/build/reps.js:11634:8
batchedUpdates@http://localhost:8000/assets/build/reps.js:5588:4
dispatchEvent@http://localhost:8000/assets/build/reps.js:15751:8
EventListener.handleEvent*listen@http://localhost:8000/assets/build/reps.js:15802:8
trapBubbledEvent@http://localhost:8000/assets/build/reps.js:15716:13
listenTo@http://localhost:8000/assets/build/reps.js:2518:12
enqueuePutListener@http://localhost:8000/assets/build/reps.js:11867:6
_createOpenTagMarkupAndPutListeners@http://localhost:8000/assets/build/reps.js:12173:12
mountComponent@http://localhost:8000/assets/build/reps.js:12122:22
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountChildren@http://localhost:8000/assets/build/reps.js:15052:29
_createContentMarkup@http://localhost:8000/assets/build/reps.js:12235:28
mountComponent@http://localhost:8000/assets/build/reps.js:12123:25
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountChildren@http://localhost:8000/assets/build/reps.js:15052:29
_createContentMarkup@http://localhost:8000/assets/build/reps.js:12235:28
mountComponent@http://localhost:8000/assets/build/reps.js:12123:25
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountChildren@http://localhost:8000/assets/build/reps.js:15052:29
_createContentMarkup@http://localhost:8000/assets/build/reps.js:12235:28
mountComponent@http://localhost:8000/assets/build/reps.js:12123:25
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponent@http://localhost:8000/assets/build/reps.js:6665:19
wrapper@http://localhost:8000/assets/build/reps.js:3834:17
mountComponent@http://localhost:8000/assets/build/reps.js:4978:19
mountComponentIntoNode@http://localhost:8000/assets/build/reps.js:1362:17

**Comment by juliandescottes** [comment]
@janodvarko @nchevobbe can any of you still reproduce the issue? 
I can't get it on master.

**Comment by nchevobbe** [comment]
I can't reproduce either

**Comment by janodvarko** [comment]
Yes, I can still see the error. I tried different Firefox profile as well as tested in Chrome.

It's weird that you can't see it, what could be different in our configs?

Honza

**Comment by nchevobbe** [comment]
@janodvarko does this happen with a "clean" expression history (no other expressions were evaluated before) ?

**Comment by janodvarko** [comment]
Yes, the error happens any time I click/expand the `Show expression packet` button.

Honza

**Comment by juliandescottes** [comment]
I have tested on OSX and Windows and I can't reproduce the issue.
Are you targeting a specific page?

The logs you attached in your first comment do not match the bundle generated locally. Are you sure you are up to date?

**Comment by juliandescottes** [comment]
![reps-propreps-bug](https://cloud.githubusercontent.com/assets/1141550/22692469/8b573582-ed3f-11e6-90b3-25e264bada77.gif)

Let me know if I am doing something wrong compared to your scenario.

**Comment by janodvarko** [comment]
> The logs you attached in your first comment do not match the bundle generated locally. Are you sure you are up to date?

OK, this was the problem. I pulled from devtools-reps and the problem is gone.

Closing this report.

Thanks!
Honza
